#!/usr/bin/env python3
"""高精細オフライン基図 (Natural Earth 50m) を Leaflet 用に整形する (dev-time のみ)。

参照ツール級の「ちゃんとした地図」をエアギャップのまま近づけるための基図。Natural Earth
(public domain) の admin-0 countries 50m を、座標精度を落とし南極除外・±180 unwrap して
``frontend/src/components/geo/ne_countries.geojson`` に出力 (Vite ?url で同一オリジン配信)。
さらに populated places から主要都市を絞って ``cityLabels.ts`` (都市名ラベル) を生成。

出典: nvkelso/natural-earth-vector (Natural Earth, public domain)。外部DLは dev-time のみ。

Usage:
    NE=https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson
    curl -s -o /tmp/ne_50m_countries.geojson $NE/ne_50m_admin_0_countries.geojson
    curl -s -o /tmp/ne_places.geojson $NE/ne_10m_populated_places_simple.geojson
    uv run python scripts/gen_ne_basemap.py /tmp/ne_50m_countries.geojson /tmp/ne_places.geojson
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

LAT_DROP_BELOW = -56.0
PRECISION = 2  # 座標小数桁 (~1.1km、基図には十分でサイズ削減)
CITY_MAX_SCALERANK = 4  # これ以下 (=主要) の都市のみラベル化
GEO_OUT = Path("frontend/src/components/geo/ne_countries.geojson")
CITY_OUT = Path("frontend/src/components/geo/cityLabels.ts")


def _unwrap(ring: list[list[float]]) -> list[list[float]]:
    if not ring:
        return ring
    out = [[round(ring[0][0], PRECISION), round(ring[0][1], PRECISION)]]
    for lon, lat in ring[1:]:
        prev = out[-1][0]
        while lon - prev > 180:
            lon -= 360
        while lon - prev < -180:
            lon += 360
        out.append([round(lon, PRECISION), round(lat, PRECISION)])
    return out


def _clean_polys(coords: list, gtype: str) -> tuple[list, float]:
    """Polygon/MultiPolygon の座標を unwrap + 精度落とし。最大緯度も返す (南極判定用)。"""
    polys = [coords] if gtype == "Polygon" else coords
    out_polys = []
    max_lat = -90.0
    for poly in polys:
        rings = [_unwrap(r) for r in poly if len(r) >= 4]
        if not rings:
            continue
        max_lat = max(max_lat, max(p[1] for p in rings[0]))
        out_polys.append(rings)
    return out_polys, max_lat


def _gen_countries(src: Path) -> None:
    fc = json.loads(src.read_text())
    feats = []
    for f in fc["features"]:
        g = f.get("geometry") or {}
        if g.get("type") not in ("Polygon", "MultiPolygon"):
            continue
        polys, max_lat = _clean_polys(g["coordinates"], g["type"])
        if not polys or max_lat < LAT_DROP_BELOW:
            continue
        props = f.get("properties", {})
        iso = props.get("ISO_A2_EH") or props.get("ISO_A2")
        if iso in ("-99", "", None):
            iso = None
        geom = (
            {"type": "Polygon", "coordinates": polys[0]}
            if len(polys) == 1
            else {"type": "MultiPolygon", "coordinates": polys}
        )
        feats.append(
            {
                "type": "Feature",
                "properties": {
                    "iso": iso,
                    "name": props.get("NAME"),
                    "name_ja": props.get("NAME_JA"),
                },
                "geometry": geom,
            }
        )
    out = {"type": "FeatureCollection", "features": feats}
    GEO_OUT.write_text(json.dumps(out, separators=(",", ":"), ensure_ascii=False), encoding="utf-8")
    print(f"wrote {GEO_OUT} ({len(feats)} countries, {GEO_OUT.stat().st_size} bytes)")


def _gen_cities(src: Path) -> None:
    fc = json.loads(src.read_text())
    cities = []
    for f in fc["features"]:
        p = f.get("properties", {})
        try:
            rank = int(p.get("scalerank", 99))
        except (TypeError, ValueError):
            rank = 99
        if rank > CITY_MAX_SCALERANK:
            continue
        coords = (f.get("geometry") or {}).get("coordinates")
        name = p.get("name")
        if not coords or not name:
            continue
        cities.append(
            {"name": name, "lat": round(coords[1], 3), "lon": round(coords[0], 3), "rank": rank}
        )
    cities.sort(key=lambda c: c["rank"])
    body = json.dumps(cities, ensure_ascii=False)
    ts = (
        "// AUTO-GENERATED by scripts/gen_ne_basemap.py — do not edit by hand.\n"
        "// 出典: Natural Earth populated_places (public domain)。主要都市ラベル (scalerank<=4)。\n"
        "export interface CityLabel { name: string; lat: number; lon: number; rank: number; }\n"
        f"export const CITY_LABELS: CityLabel[] = {body};\n"
    )
    CITY_OUT.write_text(ts, encoding="utf-8")
    print(f"wrote {CITY_OUT} ({len(cities)} cities, {CITY_OUT.stat().st_size} bytes)")


def main(countries_src: Path, places_src: Path) -> int:
    _gen_countries(countries_src)
    _gen_cities(places_src)
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("usage: gen_ne_basemap.py <countries.geojson> <places.geojson>", file=sys.stderr)
        sys.exit(2)
    sys.exit(main(Path(sys.argv[1]), Path(sys.argv[2])))
